import pandas as pd

def create_lifecycle_grouped_features():
    """Load performance tier Net New MRR features from pipeline results"""
    
    # Load performance tier data generated by the pipeline
    performance_tiers = ['high_performers', 'moderate_performers', 'underperformers']
    
    features = {}
    for tier in performance_tiers:
        file_path = f'output/{tier}/combined_results/baseline_combined_mrr_arpu_results.csv'
        try:
            tier_data = pd.read_csv(file_path)[:-1]  # Remove last row
            features[f'{tier}_net_new_mrr'] = tier_data["Net New MRR"]
            print(f"✅ Loaded {tier} Net New MRR data")
        except FileNotFoundError:
            print(f"⚠️  Warning: {tier} data not found, using zeros")
            features[f'{tier}_net_new_mrr'] = [0] * 62  # 62 months of zeros
    
    print("🎯 Performance tier features created:")
    for feature_name in features.keys():
        print(f"   - {feature_name}")
    
    return features